### ISSUE TITLE
Line 23 "mapping values are not allowed here"

### ISSUE THREAD

**Issue by tanderson1992** [jaddel/ESPHome#1]
When I validate the yaml in ESPHome, I receive an error in line 23 `Error parsing yaml file: mapping values are not allowed here`. If I completely remove the `ssid:    ap:` line, the file validates and compiles.

**Comment by 10bn** [comment]
Which configuration are you talking about?

**Comment by tanderson1992** [comment]
Sorry, at the time the Athom 15W bulb was your only configuration. That's the one that gave me the error I described above.

**Comment by 10bn** [comment]
ok, currently there will be now further development. I'll close the issue.

**Comment by mew1033** [comment]
This is still a problem, BTW. Just ran into it.
Thanks for the config for the Athom 15W bulbs though! I really appreciate it!
